;;; -*- Lisp -*-
;;;
;;; $Id$
;;;
;;; Temperley's performances of Essen folk song melodies, as described in:
;;; David Temperley "Music and Probability", MIT Press 2007

(in-package :dorys)

;;; "/Volumes/iDisk/Research/Data/EsAC/Kern/"

(defparameter *essen-perf-meters* '(

("czech01" :meter "2/4" :meter-description "simple duple")
("czech10" :meter "2/4" :meter-description "simple duple")
("czech13" :meter "3/4" :meter-description "simple triple")
("czech35" :meter "2/4" :meter-description "simple duple")
("danmark3" :meter "3/4" :meter-description "simple triple")
("danmark6" :meter "2/4" :meter-description "simple duple")
("danmark7" :meter "4/4" :meter-description "simple quadruple")
("danmark9" :meter "2/4" :meter-description "simple duple")
("deut0206" :meter "4/4" :meter-description "simple quadruple")
("deut0214" :meter "3/4" :meter-description "simple triple")
("deut0717" :meter "6/8" :meter-description "compound duple")
("deut1334" :meter "4/4" :meter-description "simple quadruple")
("elsass01" :meter "2/4" :meter-description "simple duple")
("elsass45" :meter "6/8" :meter-description "compound duple")
("elsass54" :meter "2/4" :meter-description "simple duple")
("elsass71" :meter "6/8" :meter-description "compound duple")
("france01" :meter "4/4" :meter-description "simple quadruple")
("france03" :meter "2/4" :meter-description "simple duple")
("france08" :meter "6/8" :meter-description "compound duple")
("france13" :meter "2/4" :meter-description "simple duple")
("italia02" :meter "3/4" :meter-description "simple triple")
("italia04" :meter "2/4" :meter-description "simple duple")
("italia08" :meter "6/8" :meter-description "compound duple")
("jugos003" :meter "3/2" :meter-description "simple triple")
("jugos051" :meter "4/4" :meter-description "simple quadruple")
("jugos117" :meter "6/8" :meter-description "compound duple")
("lothr017" :meter "3/4" :meter-description "simple triple")
("lothr043" :meter "2/4" :meter-description "simple duple")
("luxemb03" :meter "4/4" :meter-description "simple quadruple")
("luxemb04" :meter "2/4" :meter-description "simple duple")
("magyar21" :meter "3/4" :meter-description "simple triple")
("magyar26" :meter "3/4" :meter-description "simple triple")
("magyar29" :meter "4/4" :meter-description "simple quadruple")
("neder040" :meter "6/4" :meter-description "compound duple")
("oestr035" :meter "3/4" :meter-description "simple triple")
("oestr081" :meter "3/4" :meter-description "simple triple")
("oestr102" :meter "6/8" :meter-description "compound duple")
("polska01" :meter "6/8" :meter-description "compound duple")
("polska11" :meter "6/8" :meter-description "compound duple")
("polska22" :meter "4/4" :meter-description "simple quadruple")
("romani01" :meter "3/4" :meter-description "simple triple")
("romani09" :meter "4/4" :meter-description "simple quadruple")
("romani13" :meter "3/4" :meter-description "simple triple")
("romani22" :meter "3/8" :meter-description "simple triple")
("suisse28" :meter "4/4" :meter-description "simple quadruple")
("suisse35" :meter "2/4" :meter-description "simple duple")
("suisse57" :meter "6/8" :meter-description "compound duple")
("suisse67" :meter "3/8" :meter-description "simple triple")
("sverig01" :meter "6/8" :meter-description "compound duple")
("sverig06" :meter "4/4" :meter-description "simple quadruple")
("sverig07" :meter "4/4" :meter-description "simple quadruple")
("sverig09" :meter "6/8" :meter-description "compound duple")
("tirol03" :meter "4/4" :meter-description "simple quadruple")
("tirol06" :meter "3/4" :meter-description "simple triple")
("tirol12" :meter "3/4" :meter-description "simple triple")
("tirol14" :meter "2/4" :meter-description "simple duple")
("ukrain06" :meter "6/8" :meter-description "compound duple")
("ukrain11" :meter "4/4" :meter-description "simple quadruple")
("ukrain12" :meter "4/4" :meter-description "simple quadruple")
("ussr21" :meter "3/8" :meter-description "simple triple")
("ussr25" :meter "4/4" :meter-description "simple quadruple")
("ussr26" :meter "2/4" :meter-description "simple duple")
("ussr36" :meter "6/8" :meter-description "compound duple")))

(defun essen-of-meter (meter) 
  (remove-if-not (lambda (x) (equal x meter)) *essen-perf-meters* :key #'third))

(defun essen-named (name)
  (find name dorys::*essen-perf-meters* :test #'equal :key #'first))

