# -*- Octave -*-
# Save the vectors as times and amplitudes of a MusicKit scorefile.
function save_score(description, filename, times, velocities, instrument)
  duration = 0.075;
  handClapFilename = tilde_expand([filename ".handclap.score"]);
  [f,msg] = fopen(handClapFilename, "w");

  if(f == -1)
    error([msg, " ", handClapFilename]);
  endif

  ## retrieve the name of the file without the path to make a thread name
  basename = split(filename, "/");
  sz = size(basename);

  ## normally we handclap using a sample
  if(nargin < 5)
    instrument = "Sampler";
  endif
  
  fprintf(f, "// MusicKit scorefile %s\n", handClapFilename);
  fprintf(f, "// Generated by save_score\n");
  fprintf(f, 'info tempo: 60, title: "Handclapping to %s";\n', description);
  fprintf(f, "part handclap;\n");
  fprintf(f, 'handclap synthPatchCount:1, synthPatch:"%s";\n\n', instrument);
  fprintf(f, "BEGIN;\n");
  rhythms = diff(times);

  ## final rhythm is immaterial, so long as it's long enough for the sample
  rhythms(length(times)) = 1.0;

  noteTag = 0;
  for timeIndex = 1:length(times)
    fprintf(f, "// IOI = %6.3f\n", rhythms(timeIndex));
    fprintf(f, "t %6.3f;\n", times(timeIndex));
    fprintf(f, "handclap (%f %d) ", duration, noteTag);
    if(strcmp(instrument, "Sampler"))
      fprintf(f, "filename: \"%s\" ", "~/Library/Sounds/hihat_closed.aiff");
    elseif(strcmp(instrument, "Midi"))
      fprintf(f, "note: g3, ");
    endif
    fprintf(f, "amplitude: %f;\n", velocities(timeIndex));
    noteTag++;
  endfor
  fprintf(f, "END;\n");
  fclose(f);
endfunction


