#!/bin/sh
# convert the sound file to ascii floating point numbers 
zero=0.000000

if [ $1_x = _x ]; then
  echo "usage: $0 file.snd"
  echo "(generates file.text as ascii floating point values)"
  exit
fi

sndconvert -f 6 -o /tmp/impulses.snd $1;
outfn=`basename $1 .snd`.text
sndtofloat /tmp/impulses.snd $outfn
#trail=`tail -1 $outfn`
#echo $trail
#if [ $trail != $zero ]; then
#  i=0
#  while [ $i -lt 200 ]
#    do echo $zero >> $outfn
#       i=`expr $i + 1`
#  done
#fi
