((LAMBDA (%CONTAINER%)
    (ADD-OBJECTS
      (LIST
        (MAKE-OBJECT 'RHYTHM-PERIODICITY-PITCH :DURATION 1 :NOTE 'C4 :AMPLITUDE
          1 :RHYTHM 2
        )
        (MAKE-OBJECT 'RHYTHM-PERIODICITY-PITCH :DURATION 1 :NOTE 'C4 :AMPLITUDE
          1 :RHYTHM 1
        )
        (MAKE-OBJECT 'RHYTHM-PERIODICITY-PITCH :DURATION 1 :NOTE 'C4 :AMPLITUDE
          1 :RHYTHM 1
        )
        (MAKE-OBJECT 'RHYTHM-PERIODICITY-PITCH :DURATION 0.5 :NOTE 'C4
          :AMPLITUDE 1 :RHYTHM 0.5
        )
        (MAKE-OBJECT 'RHYTHM-PERIODICITY-PITCH :DURATION 0.5 :NOTE 'C4
          :AMPLITUDE 1 :RHYTHM 0.5
        )
        (MAKE-OBJECT 'RHYTHM-PERIODICITY-PITCH :DURATION 1 :NOTE 'C4 :AMPLITUDE
          1 :RHYTHM 1
      ) )
      %CONTAINER% NIL :COPY-FIRST NIL
    )
    %CONTAINER%
 )
  (MAKE-OBJECT '(THREAD FOO) :ID 'FOO)
)
